#pragma once

#ifdef _EDITOR

#include <filesystem>
#include <map>
#include <optional>
#include <string>
#include <vector>

// The per-model facts the world editor shows and copies into regeneration
// requests, read from <repo>/assets-work/World{N}/catalog.json. That file is
// generated by assets-work/World1/coordination/build_editor_catalog.py; its
// fields are documented in assets-work/World1/requests/README.md. Paths in it
// are relative to the repository root and use '/'.
namespace Editor::Assets
{
// Catalog models without a World object type (fauna spawned by code).
constexpr int NO_TYPE = -1;

// One row of engine-controls.md: an engine behaviour the model must keep working.
struct EngineControl
{
    std::string sourceRow;
    std::vector<std::string> controls;
    std::string requirement;
    std::optional<int> blendMesh;
    std::optional<std::string> blendMeshTexture;
};

// A texture as the BMD names it and the game file that holds it.
struct TextureLink
{
    std::string name;                    // e.g. tree.jpg
    std::string container;               // e.g. src/bin/Data/Object1/tree.OZJ
    std::vector<std::string> sharedWith; // other models that use the same container
};

// One integrated production batch that touched the model.
struct BatchInfo
{
    std::string name;
    std::string role;  // primary or compatibility
    std::string agent; // may be empty
    std::string notes; // repo path of the batch notes
    std::optional<std::string> modelDir;
    std::vector<std::string> integrationCommits;
};

struct RequestRef
{
    std::string id;
    std::string status;
    std::string assignedTo; // empty when not assigned yet
};

// The pre-rebuild model.
struct OriginalInfo
{
    std::string revision;
    std::optional<std::string> archive;
};

// The owner's own verdict after looking at the model in the client.
struct ClientReview
{
    std::string verdict; // see ClientReview.h
    std::string note;
    std::string date; // YYYY-MM-DD
};

struct CatalogModel
{
    std::string name;
    int type = NO_TYPE;
    std::string bmd;
    std::string identity;
    bool inScope = true;
    std::string exclusion; // why the model is out of the art scope; empty when in scope
    std::string status;    // accepted, blocked, in-progress or unchanged
    bool clientVerified = false;
    std::optional<ClientReview> clientReview;
    int placementCount = 0; // placements in the shipped EncTerrain file
    std::vector<TextureLink> textures;
    std::vector<EngineControl> engineControls;
    std::string currentSha256; // of the BMD when the catalog was generated
    bool bmdModified = false;
    OriginalInfo original;
    std::optional<std::string> lastBatch;
    std::optional<std::string> modelDir;
    std::vector<BatchInfo> batches; // oldest first
    std::string baselinePreview;    // offline render before the rebuild; empty when none
    std::string finalPreview;       // offline render of the current model; empty when none
    std::vector<RequestRef> requests;
};

struct Catalog
{
    int world = 0;
    std::string worldName;
    std::vector<CatalogModel> models; // typed models by type, then untyped ones by name

    const CatalogModel* FindByType(int type) const;
    const CatalogModel* FindByName(const std::string& name) const;
};

// <repo>/assets-work/World{world}: the asset folder of one world.
std::filesystem::path WorldAssetsDir(const std::filesystem::path& repoRoot, int world);
std::filesystem::path CatalogFile(const std::filesystem::path& repoRoot, int world);

// Parses catalog.json text. Returns false and fills `error` when it is not a
// catalog the editor understands.
bool ParseCatalog(const std::string& text, Catalog& out, std::string& error);

struct CatalogLoad
{
    bool fileFound = false;
    std::optional<Catalog> catalog; // set when the file was found and parsed
    std::string error;              // why catalog is empty
};

CatalogLoad LoadCatalog(const std::filesystem::path& repoRoot, int world);

// Every container the models use -> the names of the models using it (sorted).
std::map<std::string, std::vector<std::string>> TextureConsumers(const CatalogModel& model);
} // namespace Editor::Assets

#endif // _EDITOR
